name: 'Deploy site'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Dokku deploy
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: ${{ secrets.DOKKU_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: '--force'
